name: dronetanalysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - adwaita-icon-theme=49.0
  - alsa-lib=1.2.14
  - amply=0.1.6
  - annotated-types=0.7.0
  - anyio=4.11.0
  - appdirs=1.4.4
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - argparse-dataclass=2.0.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - binutils_impl_linux-64=2.44
  - bioconductor-annotationdbi=1.68.0
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-clusterprofiler=4.14.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-deseq2=1.46.0
  - bioconductor-dose=4.0.0
  - bioconductor-edger=4.4.0
  - bioconductor-enrichplot=1.26.1
  - bioconductor-fgsea=1.32.2
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicranges=1.58.0
  - bioconductor-ggtree=3.14.0
  - bioconductor-go.db=3.20.0
  - bioconductor-gosemsim=2.32.0
  - bioconductor-impute=1.80.0
  - bioconductor-iranges=2.40.0
  - bioconductor-keggrest=1.46.0
  - bioconductor-limma=3.62.1
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-org.dm.eg.db=3.20.0
  - bioconductor-preprocesscore=1.68.0
  - bioconductor-qvalue=2.38.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-treeio=1.30.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - biopython=1.85
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - click=8.3.1
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.3
  - conda-inject=1.3.2
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - contourpy=1.3.3
  - cpython=3.13.7
  - curl=8.14.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docutils=0.22.3
  - double-conversion=3.3.1
  - dpath=2.2.0
  - eido=0.2.4
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.1.0
  - gdk-pixbuf=2.44.4
  - gfortran_impl_linux-64=15.1.0
  - git-lfs=3.7.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.86.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - graphviz=14.0.4
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx_impl_linux-64=15.1.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - immutables=0.21
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jq=1.5
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.2
  - libclang13=21.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.9.1
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.2
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - librsvg=2.60.0
  - libsanitizer=15.1.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libuv=1.51.0
  - libvulkan-loader=1.4.313.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxml2-devel=2.15.0
  - libxslt=1.1.43
  - libzlib=1.3.1
  - logmuse=0.2.8
  - make=4.4.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.4
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.2
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - pephubclient=0.4.4
  - peppy=0.40.8
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - plac=1.4.5
  - platformdirs=4.4.0
  - pluggy=1.6.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.8.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - pytest=9.0.1
  - python=3.13.9
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.13.7
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - r-abind=1.4_8
  - r-ape=5.8_1
  - r-aplot=0.2.9
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-checkmate=2.3.3
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-commonmark=2.0.0
  - r-corrplot=0.95
  - r-cowplot=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.3
  - r-crosstalk=1.2.2
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-deldir=2.0_4
  - r-deoptimr=1.1_4
  - r-desc=1.4.3
  - r-devtools=2.4.6
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-doparallel=1.0.17
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-dynamictreecut=1.63_1
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastcluster=1.3.0
  - r-fastmap=1.2.0
  - r-fastmatch=1.1_6
  - r-fit.models=0.64
  - r-fontawesome=0.5.3
  - r-foreach=1.5.2
  - r-foreign=0.8_90
  - r-formatr=1.14
  - r-formula=1.2_5
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.1.4
  - r-gert=2.1.5
  - r-ggforce=0.5.0
  - r-ggfun=0.2.0
  - r-ggnewscale=0.5.2
  - r-ggplot2=4.0.0
  - r-ggplotify=0.1.3
  - r-ggrepel=0.9.6
  - r-ggtangle=0.0.8
  - r-gh=1.5.0
  - r-gitcreds=0.1.2
  - r-glue=1.8.0
  - r-gprofiler2=0.2.3
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gson=0.1.0
  - r-gtable=0.3.6
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-hmisc=5.2_4
  - r-hms=1.1.3
  - r-htmltable=2.4.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpgd=2.0.4
  - r-httpuv=1.6.16
  - r-httr=1.4.7
  - r-httr2=1.2.1
  - r-igraph=2.1.4
  - r-ini=0.3.1
  - r-interp=1.1_6
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_11
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-latticeextra=0.6_31
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.4
  - r-locfit=1.5_9.12
  - r-magrittr=2.0.4
  - r-mass=7.3_65
  - r-matrix=1.7_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-munsell=0.5.1
  - r-mvtnorm=1.3_3
  - r-nlme=3.1_168
  - r-nnet=7.3_20
  - r-openssl=2.3.4
  - r-patchwork=1.3.2
  - r-pcapp=2.0_5
  - r-pheatmap=1.0.13
  - r-pillar=1.11.1
  - r-pkgbuild=1.4.8
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.3
  - r-pkgload=1.4.1
  - r-plogr=0.2.0
  - r-plotly=4.11.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-profvis=0.4.0
  - r-progress=1.2.3
  - r-promises=1.3.3
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-r.methodss3=1.8.2
  - r-r.oo=1.27.1
  - r-r.utils=2.13.0
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=15.0.2_2
  - r-rcppeigen=0.3.4.0.2
  - r-rcurl=1.98_1.17
  - r-readr=2.1.5
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rlist=0.4.6.2
  - r-rmarkdown=2.30
  - r-robust=0.7_5
  - r-robustbase=0.99_6
  - r-roxygen2=7.3.3
  - r-rpart=4.1.24
  - r-rprojroot=2.1.1
  - r-rrcov=1.7_7
  - r-rsqlite=2.4.3
  - r-rstudioapi=0.17.1
  - r-rversions=3.0.0
  - r-s7=0.2.0
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-scatterpie=0.2.6
  - r-sessioninfo=1.2.3
  - r-shiny=1.11.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-statmod=1.5.0
  - r-stringi=1.8.7
  - r-stringr=1.5.2
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.3.1
  - r-testthat=3.2.3
  - r-textshaping=1.0.4
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidytree=0.4.6
  - r-tinytex=0.57
  - r-tweenr=2.0.3
  - r-tzdb=0.5.0
  - r-unigd=0.1.2
  - r-urlchecker=1.0.1
  - r-usethis=3.2.1
  - r-utf8=1.2.6
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.6
  - r-waldo=0.6.2
  - r-wgcna=1.73
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.53
  - r-xml=3.99_0.17
  - r-xml2=1.4.0
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-yulab.utils=0.2.1
  - r-zip=2.3.3
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - reretry=0.11.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rpds-py=0.27.1
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - slack-sdk=3.38.0
  - slack_sdk=3.38.0
  - smart_open=7.5.0
  - smmap=5.0.2
  - snakemake=9.13.7
  - snakemake-interface-common=1.22.0
  - snakemake-interface-executor-plugins=9.3.9
  - snakemake-interface-logger-plugins=2.0.0
  - snakemake-interface-report-plugins=1.3.0
  - snakemake-interface-scheduler-plugins=2.0.2
  - snakemake-interface-storage-plugins=4.2.3
  - snakemake-minimal=9.13.7
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - sysroot_linux-64=2.34
  - tabulate=0.9.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - throttler=1.2.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ubiquerg=0.8.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - veracitools=0.1.3
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - yaml=0.2.5
  - yq=3.4.3
  - yte=1.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - anndata==0.12.2
      - array-api-compat==1.12.0
      - crc32c==2.7.1
      - donfig==0.8.1.post1
      - formulaic==1.2.1
      - formulaic-contrasts==1.0.0
      - h5py==3.14.0
      - interface-meta==1.3.0
      - legacy-api-wrap==1.4.1
      - narwhals==2.7.0
      - natsort==8.4.0
      - numcodecs==0.16.3
      - pydeseq2==0.5.2
      - session-info==1.0.1
      - stdlib-list==0.11.1
      - wrapt==2.0.0rc4
      - zarr==3.1.3
prefix: /tmp/global2/gthornes/miniforge3/envs/dronetanalysis
