# config.yaml
# ------------------------------------------------------------------------------
# Centralized configuration
# ------------------------------------------------------------------------------
timestamp_fmt: "%Y%m%d_%H%M%S"
analysis_params:
  permutation_repeats: 100
  use_filtered_network: true
  root: "results"
  feature_steps: ["closeness", "degree", "centrality", "betweenness"]

project_dirs:
  rawdata_dir: "dataset/raw"
  processed_data_dir: "dataset/processed"
  subset_data_dir: "dataset/subset"
  test_data_dir: "dataset/test"
output_dirs:
  figures_dir: "results/figures"
  tables_dir: "results/tables"
  logs_dir: "results/logs"
  reports_dir: "results/reports"
  wgcna_dir: "results/WGCNA"
  GWENA_dir: "results/GWENA"
  spearman_dir: "results/spearman_correlation"
  network_features_dir: "results/network_features"
raw_files:
  rawcount_file: "dataset/raw/RawCounts_noY_CPM1_head_hsctrl_onlyGEMMAsamples_Mar21.21.txt"
  rawmeta_file: "dataset/raw/Info_RawCounts_CPM1_head_hsctrl_Jul9.20.txt"
  voom_surrogate_files:
    - "dataset/raw/VOOM_surrogates/TMM_Voom_sv1_10.txt"
    - "dataset/raw/VOOM_surrogates/TMM_Voom_sv2_10.txt"
    - "dataset/raw/VOOM_surrogates/TMM_Voom_sv3_10.txt"
    - "dataset/raw/VOOM_surrogates/TMM_Voom_sv4_10.txt"
  vst_surrogate_files:
    - "dataset/raw/VST_surrogates/VST_sv1_10.txt"
    - "dataset/raw/VST_surrogates/VST_sv2_10.txt"
    - "dataset/raw/VST_surrogates/VST_sv3_10.txt"
processed_files:
  voom_processed_files:
    - "dataset/processed/VOOM/voomdataCtrl.txt"
    - "dataset/processed/VOOM/voomdataHS.txt"
  vst_processed_files:
    - "dataset/processed/VST/VSTdataCtrl.txt"
    - "dataset/processed/VST/VSTdataHS.txt"

spearman_correlation_files:
  permutation_files:
    - "results/spearman_correlation/permutation_test"
network_feature_files:
  soft_threshold_files:
    - "results/network_features/soft_threshold/unsigned/unsigned_soft_thresholded_adjacency_matrix.csv"

# arguments for each steps
genes:
- FBgn0031081
- FBgn0031082

subset_expr_matrix:
  output_dirs: "results/gene_wise/expr"
  desc_body: ["_1stquin_expr", "_5thquin_expr"]
  suffix: "csv"

create_network:
  output_dirs: "results/gene_wise/networks"
  desc_body: ["_1stquin_network", "_5thquin_network"]
  suffix: "csv"

cal_diff_networks:
  output_dirs: "results/gene_wise/networks"
  desc_body: "_diff_network"
  suffix: "csv"

cal_network_features:
  output_dirs: "results/gene_wise/features"
  desc_body: ["_feats_diff_network", "_feats_1stquin_network", "_feats_5thquin_network"]
  suffix: "csv"

subset_features_neighbors:
  output_dirs: "results/gene_wise/neighbors"
  desc_body: ["_feats_1stlayer_diff_network", "_feats_2ndlayer_diff_network",
              "_feats_1stlayer_1stquin_network", "_feats_2ndlayer_1stquin_network",
              "_feats_1stlayer_5thquin_network", "_feats_2ndlayer_5thquin_network"]
  neighbour_layers: [1,2]